// ==UserScript==
// @name         小红书创作平台数据采集器
// @namespace    http://tampermonkey.net/
// @version      1.0.0
// @description  自动采集小红书创作平台笔记数据（基础信息、数据指标、内容）
// @author       Generated by Claude Code
// @match        https://creator.xiaohongshu.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // ==================== 配置区 ====================
    const CONFIG = {
        API_URL: '/api/galaxy/creator/datacenter/note/analyze/list',
        LOCAL_API: 'http://localhost:3000',
        ENABLE_LOCAL_SYNC: true,
        AUTO_COLLECT: true,

        // 防检测配置
        PAGE_DELAY_MIN: 2000,        // 翻页最小延迟 2秒
        PAGE_DELAY_MAX: 5000,        // 翻页最大延迟 5秒
        PAUSE_PROBABILITY: 0.15,     // 15% 概率随机停顿
        PAUSE_TIME_MIN: 3000,        // 停顿最小时长 3秒
        PAUSE_TIME_MAX: 10000,       // 停顿最大时长 10秒
        ENABLE_SCROLL: true,         // 启用随机滚动
    };

    // ==================== 全局变量 ====================
    let allNotesData = [];           // 所有笔记数据
    let currentPage = 0;             // 当前页码
    let totalNotes = 0;              // 总笔记数
    let collectedPages = new Set();  // 已采集页码
    let isAutoCollecting = false;    // 是否正在自动采集
    let isPageLoading = false;       // 页面是否正在加载
    let enableDataCapture = true;    // 默认启用数据拦截
    let isPanelCollapsed = false;    // 面板是否折叠

    // 拖拽相关
    let isDragging = false;
    let currentX, currentY, initialX, initialY;
    let xOffset = 0, yOffset = 0;

    // ==================== 控制面板 ====================
    function createControlPanel() {
        const panel = document.createElement('div');
        panel.id = 'xhs-scraper-panel';
        panel.innerHTML = `
            <div id="panel-content" style="
                position: fixed;
                top: 20px;
                right: 20px;
                background: white;
                padding: 20px 24px;
                border-radius: 24px;
                box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06);
                border: 1px solid #f1f5f9;
                z-index: 999999;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                min-width: 320px;
                transition: all 0.3s ease;
            ">
                <div id="drag-header" style="
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                    margin-bottom: 16px;
                    padding-bottom: 16px;
                    border-bottom: 1px solid #f1f5f9;
                    cursor: move;
                ">
                    <div style="display: flex; align-items: center;">
                        <div style="
                            width: 32px;
                            height: 32px;
                            background: linear-gradient(135deg, #ff2442 0%, #ff6348 100%);
                            border-radius: 8px;
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            color: white;
                            font-weight: bold;
                            font-size: 16px;
                            margin-right: 8px;
                            box-shadow: 0 4px 6px -1px rgba(255, 36, 66, 0.3);
                        ">小</div>
                        <div style="display: flex; flex-direction: column;">
                            <div style="display: flex; align-items: center; gap: 6px;">
                                <span style="font-size: 16px; font-weight: 900; color: #1e293b; letter-spacing: -0.01em;">小红书采集器</span>
                                <span style="font-size: 10px; color: #64748b; font-weight: 600; padding: 2px 6px; background: #f1f5f9; border-radius: 4px;">v1.0.0</span>
                            </div>
                            <span style="font-size: 9px; color: #94a3b8; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;">DATA COLLECTOR</span>
                        </div>
                    </div>
                    <button id="toggle-btn" style="
                        width: 24px;
                        height: 24px;
                        background: #f8fafc;
                        border: 1px solid #e2e8f0;
                        border-radius: 8px;
                        cursor: pointer;
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        transition: all 0.3s;
                        font-size: 14px;
                    ">−</button>
                </div>

                <div id="panel-body" style="transition: all 0.3s ease;">
                    <div style="margin-bottom: 16px;">
                        <div style="font-size: 11px; margin-bottom: 6px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">
                            当前页码: <span id="current-page" style="font-weight: 900; color: #ff2442;">0</span>
                        </div>
                        <div style="font-size: 11px; margin-bottom: 6px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">
                            已采集页数: <span id="page-count" style="font-weight: 900; color: #10b981;">0</span>
                        </div>
                        <div style="font-size: 11px; margin-bottom: 6px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">
                            笔记数量: <span id="note-count" style="font-weight: 900; color: #10b981;">0</span> / <span id="total-notes" style="font-weight: 900; color: #64748b;">0</span>
                        </div>
                    </div>

                    <button id="start-collect-btn" style="
                        width: 100%;
                        padding: 12px;
                        background: #ff2442;
                        color: white;
                        border: none;
                        border-radius: 12px;
                        font-weight: 900;
                        cursor: pointer;
                        font-size: 13px;
                        transition: all 0.3s;
                        margin-bottom: 8px;
                        box-shadow: 0 1px 3px 0 rgba(0,0,0,0.1);
                    ">▶️ 开始采集</button>

                    <button id="export-btn" style="
                        width: 100%;
                        padding: 12px;
                        background: #10b981;
                        color: white;
                        border: none;
                        border-radius: 12px;
                        font-weight: 900;
                        cursor: pointer;
                        font-size: 13px;
                        transition: all 0.3s;
                        margin-bottom: 8px;
                        box-shadow: 0 1px 3px 0 rgba(0,0,0,0.1);
                    ">💾 导出数据</button>

                    <button id="clear-btn" style="
                        width: 100%;
                        padding: 10px;
                        background: #f8fafc;
                        color: #64748b;
                        border: 1px solid #e2e8f0;
                        border-radius: 12px;
                        cursor: pointer;
                        font-size: 12px;
                        font-weight: 700;
                        transition: all 0.3s;
                    ">🗑️ 清空数据</button>
                </div>
            </div>
        `;
        document.body.appendChild(panel);

        // 绑定事件
        document.getElementById('toggle-btn').addEventListener('click', togglePanel);
        document.getElementById('start-collect-btn').addEventListener('click', toggleAutoCollect);
        document.getElementById('export-btn').addEventListener('click', exportData);
        document.getElementById('clear-btn').addEventListener('click', clearData);

        // 拖拽功能
        const dragHeader = document.getElementById('drag-header');
        const panelContent = document.getElementById('panel-content');

        dragHeader.addEventListener('mousedown', dragStart);
        document.addEventListener('mousemove', drag);
        document.addEventListener('mouseup', dragEnd);

        function dragStart(e) {
            if (e.target.closest('#toggle-btn')) return;
            initialX = e.clientX - xOffset;
            initialY = e.clientY - yOffset;
            isDragging = true;
        }

        function drag(e) {
            if (isDragging) {
                e.preventDefault();
                currentX = e.clientX - initialX;
                currentY = e.clientY - initialY;
                xOffset = currentX;
                yOffset = currentY;
                panelContent.style.transform = `translate(${currentX}px, ${currentY}px)`;
            }
        }

        function dragEnd() {
            isDragging = false;
        }
    }

    // 切换面板
    function togglePanel() {
        isPanelCollapsed = !isPanelCollapsed;
        const panelBody = document.getElementById('panel-body');
        const toggleBtn = document.getElementById('toggle-btn');

        if (isPanelCollapsed) {
            panelBody.style.maxHeight = '0';
            panelBody.style.opacity = '0';
            panelBody.style.overflow = 'hidden';
            toggleBtn.textContent = '+';
        } else {
            panelBody.style.maxHeight = '500px';
            panelBody.style.opacity = '1';
            panelBody.style.overflow = 'visible';
            toggleBtn.textContent = '−';
        }
    }

    // 更新面板
    function updatePanel() {
        const currentPageEl = document.getElementById('current-page');
        const pageCountEl = document.getElementById('page-count');
        const noteCountEl = document.getElementById('note-count');
        const totalNotesEl = document.getElementById('total-notes');

        if (currentPageEl) currentPageEl.textContent = currentPage;
        if (pageCountEl) pageCountEl.textContent = collectedPages.size;
        if (noteCountEl) noteCountEl.textContent = allNotesData.length;
        if (totalNotesEl) totalNotesEl.textContent = totalNotes;
    }

    // ==================== 数据拦截 ====================
    const originalFetch = window.fetch;
    window.fetch = function(...args) {
        return originalFetch.apply(this, args).then(response => {
            if (enableDataCapture && args[0].includes(CONFIG.API_URL)) {
                response.clone().json().then(data => {
                    processNoteData(data);
                }).catch(err => {
                    console.error('❌ 解析数据失败:', err);
                });
            }
            return response;
        });
    };

    // XHR 拦截
    const originalOpen = XMLHttpRequest.prototype.open;
    const originalSend = XMLHttpRequest.prototype.send;

    XMLHttpRequest.prototype.open = function(method, url) {
        this._url = url;
        this._method = method;
        return originalOpen.apply(this, arguments);
    };

    XMLHttpRequest.prototype.send = function() {
        this.addEventListener('load', function() {
            if (!enableDataCapture) return;

            if (this._url && this._url.includes(CONFIG.API_URL)) {
                try {
                    const responseData = JSON.parse(this.responseText);
                    processNoteData(responseData);
                } catch (e) {
                    console.error('❌ 解析响应数据失败:', e);
                }
            }
        });
        return originalSend.apply(this, arguments);
    };

    // 处理笔记数据
    function processNoteData(responseData) {
        console.log('🎯 拦截到笔记数据:', responseData);

        if (responseData.success && responseData.data && responseData.data.note_infos) {
            const notes = responseData.data.note_infos;
            const total = responseData.data.total;

            // 去重：检查是否已存在
            const newNotes = notes.filter(note =>
                !allNotesData.some(existing => existing.id === note.id)
            );

            allNotesData.push(...newNotes);
            totalNotes = total;

            // 延迟获取页码
            setTimeout(() => {
                // 从 URL 中提取页码
                const urlParams = new URLSearchParams(window.location.search);
                const pageNum = parseInt(urlParams.get('page_num')) || 1;

                if (pageNum > 0) {
                    currentPage = pageNum;
                    collectedPages.add(pageNum);
                    console.log(`✅ 第 ${pageNum} 页数据已采集，本页 ${newNotes.length} 条，总计 ${allNotesData.length}/${totalNotes} 条`);
                }
                updatePanel();
            }, 500);
        }
    }

    // ==================== 自动采集 ====================
    function toggleAutoCollect() {
        if (isAutoCollecting) {
            stopAutoCollect();
        } else {
            startAutoCollect();
        }
    }

    function startAutoCollect() {
        isAutoCollecting = true;
        enableDataCapture = true;

        const btn = document.getElementById('start-collect-btn');
        btn.textContent = '⏸️ 停止采集';
        btn.style.background = '#ef4444';

        console.log('🚀 开始自动采集');

        setTimeout(() => {
            clickNextPageWithWait();
        }, 1000);
    }

    function stopAutoCollect() {
        isAutoCollecting = false;

        const btn = document.getElementById('start-collect-btn');
        btn.textContent = '▶️ 开始采集';
        btn.style.background = '#ff2442';

        console.log('⏹️ 已停止采集');
    }

    async function clickNextPageWithWait() {
        if (!isAutoCollecting) return;

        if (isPageLoading) {
            setTimeout(clickNextPageWithWait, 1000);
            return;
        }

        // 检查是否已采集完成
        if (allNotesData.length >= totalNotes && totalNotes > 0) {
            console.log('✅ 所有数据已采集完成！');
            stopAutoCollect();
            alert(`采集完成！共 ${allNotesData.length} 条笔记数据`);
            return;
        }

        // 模拟人类行为
        if (CONFIG.ENABLE_SCROLL) {
            await scrollToBottom();
        }
        await randomPause();

        const clicked = clickNextPage();

        if (clicked) {
            isPageLoading = true;
            const lastCount = allNotesData.length;

            // 等待数据加载
            waitForDataLoad(lastCount);
        }
    }

    function clickNextPage() {
        // 查找下一页按钮
        const nextButtonSelectors = [
            '.arco-pagination-item-next:not(.arco-pagination-item-disabled)',
            'button[class*="next"]:not([disabled])',
            'li[class*="next"]:not([class*="disabled"]) button',
            '.ant-pagination-next:not(.ant-pagination-disabled)',
        ];

        for (const selector of nextButtonSelectors) {
            const btn = document.querySelector(selector);
            if (btn && !btn.disabled && !btn.classList.contains('arco-pagination-item-disabled')) {
                console.log('👆 点击下一页');
                btn.click();
                return true;
            }
        }

        console.log('⚠️ 未找到下一页按钮，采集完成');
        stopAutoCollect();
        alert(`采集完成！共 ${allNotesData.length} 条笔记数据`);
        return false;
    }

    function waitForDataLoad(lastCount) {
        let checkCount = 0;
        const maxChecks = 30;

        const checkInterval = setInterval(() => {
            checkCount++;

            const hasNewData = allNotesData.length > lastCount;

            if (hasNewData) {
                clearInterval(checkInterval);
                isPageLoading = false;

                const delay = Math.random() * (CONFIG.PAGE_DELAY_MAX - CONFIG.PAGE_DELAY_MIN) + CONFIG.PAGE_DELAY_MIN;
                console.log(`⏳ 等待 ${(delay/1000).toFixed(1)} 秒后继续...`);
                setTimeout(clickNextPageWithWait, delay);
            } else if (checkCount >= maxChecks) {
                clearInterval(checkInterval);
                isPageLoading = false;
                setTimeout(clickNextPageWithWait, 2000);
            }
        }, 1000);
    }

    // 滚动到底部
    function scrollToBottom() {
        return new Promise((resolve) => {
            const scrollHeight = document.documentElement.scrollHeight;
            const randomScroll = Math.random() * 300 + 100;
            const targetScroll = scrollHeight - randomScroll;

            window.scrollTo({
                top: targetScroll,
                behavior: 'smooth'
            });

            setTimeout(resolve, Math.random() * 500 + 300);
        });
    }

    // 随机停顿
    function randomPause() {
        return new Promise((resolve) => {
            const shouldPause = Math.random() < CONFIG.PAUSE_PROBABILITY;
            if (shouldPause) {
                const pauseTime = Math.random() * (CONFIG.PAUSE_TIME_MAX - CONFIG.PAUSE_TIME_MIN) + CONFIG.PAUSE_TIME_MIN;
                console.log(`👀 模拟查看内容，停顿 ${(pauseTime/1000).toFixed(1)} 秒...`);
                setTimeout(resolve, pauseTime);
            } else {
                resolve();
            }
        });
    }

    // ==================== 数据导出 ====================
    function exportData() {
        if (allNotesData.length === 0) {
            alert('暂无数据，请先采集数据');
            return;
        }

        const menu = document.createElement('div');
        menu.style.cssText = `
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: white;
            padding: 24px;
            border-radius: 16px;
            box-shadow: 0 10px 25px rgba(0,0,0,0.2);
            z-index: 9999999;
            min-width: 300px;
        `;

        menu.innerHTML = `
            <h3 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 900;">选择导出格式</h3>
            <button id="export-json" style="width: 100%; padding: 12px; margin-bottom: 8px; background: #3b82f6; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 700;">📄 JSON 格式</button>
            <button id="export-csv" style="width: 100%; padding: 12px; margin-bottom: 8px; background: #10b981; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 700;">📊 CSV 格式</button>
            <button id="sync-local" style="width: 100%; padding: 12px; margin-bottom: 8px; background: #8b5cf6; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 700;">🔄 同步到本地服务</button>
            <button id="cancel-export" style="width: 100%; padding: 10px; background: #f1f5f9; color: #64748b; border: none; border-radius: 8px; cursor: pointer; font-weight: 700;">取消</button>
        `;

        document.body.appendChild(menu);

        document.getElementById('export-json').addEventListener('click', () => {
            downloadJSON();
            document.body.removeChild(menu);
        });

        document.getElementById('export-csv').addEventListener('click', () => {
            downloadCSV();
            document.body.removeChild(menu);
        });

        document.getElementById('sync-local').addEventListener('click', () => {
            syncToLocal();
            document.body.removeChild(menu);
        });

        document.getElementById('cancel-export').addEventListener('click', () => {
            document.body.removeChild(menu);
        });
    }

    function downloadJSON() {
        const dataStr = JSON.stringify(allNotesData, null, 2);
        const blob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `xiaohongshu_notes_${Date.now()}.json`;
        a.click();
        URL.revokeObjectURL(url);
        console.log('✅ JSON 文件已下载');
    }

    function downloadCSV() {
        const headers = ['笔记ID', '标题', '类型', '发布时间', '阅读量', '点赞数', '收藏数', '评论数', '分享数', '曝光量', '平均观看时长', '涨粉数', '封面点击率'];
        const rows = allNotesData.map(note => [
            note.id || '',
            (note.title || '').replace(/"/g, '""'),
            note.type === 2 ? '视频' : '图文',
            note.post_time ? new Date(note.post_time).toLocaleString('zh-CN') : '',
            note.read_count || 0,
            note.like_count || 0,
            note.fav_count || 0,
            note.comment_count || 0,
            note.share_count || 0,
            note.imp_count || 0,
            note.view_time_avg || 0,
            note.increase_fans_count || 0,
            note.coverClickRate || 0,
        ]);

        const csvContent = [
            headers.join(','),
            ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
        ].join('\n');

        const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `xiaohongshu_notes_${Date.now()}.csv`;
        a.click();
        URL.revokeObjectURL(url);
        console.log('✅ CSV 文件已下载');
    }

    function syncToLocal() {
        const btn = document.getElementById('export-btn');
        const originalText = btn.textContent;

        btn.textContent = '⏳ 同步中...';
        btn.disabled = true;

        fetch(`${CONFIG.LOCAL_API}/api/sync/xiaohongshu/notes`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                notes: allNotesData,
                total: allNotesData.length,
                timestamp: Date.now()
            })
        })
        .then(res => res.json())
        .then(data => {
            console.log('✅ 同步成功:', data);
            alert(`同步成功！共 ${allNotesData.length} 条数据`);
        })
        .catch(err => {
            console.error('❌ 同步失败:', err);
            alert('同步失败，请检查本地服务是否启动\n\n启动方法：\n1. 进入脚本目录\n2. 运行: npm install\n3. 运行: npm start');
        })
        .finally(() => {
            btn.textContent = originalText;
            btn.disabled = false;
        });
    }

    // 清空数据
    function clearData() {
        if (confirm('确定要清空所有数据吗？')) {
            allNotesData = [];
            currentPage = 0;
            totalNotes = 0;
            collectedPages.clear();
            updatePanel();
            console.log('🗑️ 数据已清空');
        }
    }

    // ==================== 初始化 ====================
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', createControlPanel);
    } else {
        createControlPanel();
    }

    console.log('✅ 小红书数据采集器已启动');
    console.log('📌 使用说明：');
    console.log('   1. 点击"▶️ 开始采集"自动翻页采集');
    console.log('   2. 或手动翻页，脚本会自动拦截数据');
    console.log('   3. 采集完成后点击"💾 导出数据"');
    console.log('   4. 可选择 JSON、CSV 格式或同步到本地服务');
})();
